### ISSUE TITLE
output file "data/output/logitregres.csv"  contains the survived values other than {0,1}

### ISSUE THREAD

**Issue by srini09** [agconti/kaggle-titanic#18]
Thanks for the great article and code. I see that direct submission of output file to kaggle results in error and it says Survived column values must be either 0 or 1.

Am I missing something? Should I have a cutoff and turn them in to 0 or 1?

**Comment by vincentgc** [comment]
The cutoff should be 0.

**Comment by srini09** [comment]
Thanks. Closing the issue.
