### ISSUE TITLE
Logistic Regression

### ISSUE THREAD

**Issue by bharathcan** [agconti/kaggle-titanic#25]
Good sir, It really helped a lot but sir we can use logistic Regression instead of going complex

**Comment by thisisashwinraj** [comment]
Using Random Forest and SVM gives a better score than using Logistic Regression or any other model.
This screenshot is taken from a kaggle notebook.

![outout](https://user-images.githubusercontent.com/62590141/77730943-dbaffa00-7027-11ea-8831-f3307e33b384.JPG)
