### ISSUE TITLE
sharey for subplots

### ISSUE THREAD

**Issue by zunayed** [agconti/kaggle-titanic#7]
Not sure if you're original intention was to show the Y axis for all your subplots in `input 14` but if it wasn't you can pass in `sharey=True` into `df.plot()` function to eliminate the redundant axes. 

![example](http://i.imgur.com/FRtUweN.png)

Awesome work on the notebook btw!

**Comment by agconti** [comment]
@zunayed thanks!

I think this is  a good idea; would you mind making a pull request :smile: ?

**Comment by agconti** [comment]
Closing, since this issue has gone stale and because sharing the Y axises for subplots was not the original intention.
