### ISSUE TITLE
Column headers are now capitalized 

### ISSUE THREAD

**Issue by thearpitgupta** [agconti/kaggle-titanic#8]
Looks like column headers in the training data set are now capitalized. See here
http://www.kaggle.com/c/titanic-gettingStarted/download/train.csv
It's not capitalized in the data set used used in the repo https://github.com/agconti/kaggle-titanic/blob/master/data/train.csv 
Wonder if Kaggle changed the data set and intentionally made this change. Anyways, if you want I am happy to submit a PR that works with capitalized column names. Let me know. Thanks. 

PS - Great work.

**Comment by agconti** [comment]
@thearpitgupta that would be great; please do.  They must have changed this data set recently.

**Comment by thearpitgupta** [comment]
Here is the PR to fix this issue https://github.com/agconti/kaggle-titanic/pull/9
I re-ran all the commands in the Ipython notebook to make sure there are no errors. You can see the fixed python notebook on nbviewer here 
http://nbviewer.ipython.org/github/thearpitgupta/kaggle-titanic/blob/fix_for_capitalized_column_headers/Titanic.ipynb

Let me know if anything looks off.
